config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get 'faq', to: 'application#faq'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'new_idea', to: 'application#new_idea'
  get 'agb', to: 'application#agb'

  devise_for :users
  
  resources :users, except: [:create, :new]
  resources :news
  resources :links
  resources :pictures
  resources :pages, except: [:create, :show, :new, :destroy]

  resources :programs do
    member do
      post :rate
      get :add_existing_entry, controller: :program_entries
      get :add_new_entry, controller: :program_entries
      post :done
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :entries do
    collection do
      get :tags
      get :not_published
      get :check_duplicates
    end

    member do
      post :plan
      post :rate
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :program_entries, only: [:destroy] do
    member do
      post :move_up
      post :move_down
      post :destroy_final
      post :keep
    end
  end

  resources :comments, only: [:destroy] do
    member do
      post :publish
      post :destroy_final
      post :keep
    end
  end

  resources :attachments, only: [:destroy] do
    member do
      post :destroy_final
      post :keep
    end
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  before_action :authorize_user, except: [:index, :show, :plan]
  before_action :authorize_moderator, only: [:not_published, :publish, :keep, :destroy_final]
  before_action :load_descriptions, only: [:index, :new, :edit]

  def index

    @plan_start = (session[:plan_start] == nil) ? [] : session[:plan_start]
    @plan_main = (session[:plan_main] == nil) ? [] : session[:plan_main]
    @plan_end = (session[:plan_end] == nil) ? [] : session[:plan_end]
    @plan = (@plan_start.size() != 0) || (@plan_main.size() != 0) || (@plan_end.size() != 0)

    @hide_programs = false
    @only_programs = false
    @shown_programs = []
    if params[:filterrific] != nil
      if params[:filterrific]["with_part_start"] == "1" then @hide_programs = true end
      if params[:filterrific]["with_part_main"] == "1" then @hide_programs = true end
      if params[:filterrific]["with_part_end"] == "1" then @hide_programs = true end
      if params[:filterrific]["only_programs"] == "1" then @only_programs = true end
    elsif session[:shared_key] != nil
      if session[:shared_key]["with_part_start"] == 1 then @hide_programs = true end
      if session[:shared_key]["with_part_main"] == 1 then @hide_programs = true end
      if session[:shared_key]["with_part_end"] == 1 then @hide_programs = true end
      if session[:shared_key]["only_programs"] == 1 then @only_programs = true end
    end

    if @only_programs
      @filterrific = initialize_filterrific(
        Program,
        params[:filterrific],
        select_options: {
          sorted_by: Entry.options_for_sorted_by,
          num_group: Entry.options_for_num_group,
          num_age: Entry.options_for_num_age,
          num_time: Entry.options_for_num_time
        },
        persistence_id: 'shared_key'
      ) or return 
      @entries = @filterrific.find.where(done: true, published: true).paginate(:page => params[:page], :per_page => 20)
    else
      @filterrific = initialize_filterrific(
        Entry,
        params[:filterrific],
        select_options: {
          sorted_by: Entry.options_for_sorted_by,
          num_group: Entry.options_for_num_group,
          num_age: Entry.options_for_num_age,
          num_time: Entry.options_for_num_time
        },
        persistence_id: 'shared_key'
      ) or return
      @entries = @filterrific.find.where(independent: true, published: true).paginate(:page => params[:page], :per_page => 20)
    end

    respond_to do |format|
      format.html
      format.js
    end

    rescue ActiveRecord::RecordNotFound => e
      puts "Ein Fehler ist aufgetreten und der Filter wurde zurueckgesetzt: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return

  end

  def check_duplicates
    data = []
    entries = Entry.search_query(params[:titles].gsub(',', ' '))
    entries.each do |entry|
      str = OpenStruct.new
      str.title = entry.title
      str.url = entry.id
      data << str
    end

    respond_to do |format|
      format.json { 
        render json: data
      }
    end
  end

  def show
    @entry = Entry.find(params[:id])

    if session[:add_ex_entry]
      program = Program.find(session[:add_ex_entry])
      order = session[:add_ex_entry_order]
      session.delete(:add_ex_entry)
      session.delete(:add_ex_entry_order)

      last_program_entry = ProgramEntry.where(program: program).where(order: (order..(order+99))).order(:order).last
      order = last_program_entry.order+1 if last_program_entry
      @program_entry = ProgramEntry.create(program: program, order: order, entry: @entry)
      program = update_program_attributes(program)
      program.save
      redirect_to @program_entry.program
    else
      if not @entry.published
        flash[:alert] = "Dieser Eintrag muss noch von einem Moderator veroeffentlicht werden, bevor er in der Suche erscheint."
      end

      if user_signed_in? and current_user.is_moderator?
        if not @entry.delete_comment == nil and @entry.programs.count > 0
          flash[:error] = "Achtung: Dieser Eintrag kommt in Gruppenstunden vor. Falls er geloescht wird, fehlen diesen Gruppenstunden eventuell wichtige Teile!"
        end
      end

      respond_to do |format|
        format.html
        format.pdf do
          render  :pdf => "Spika_Eintrag",
                  :template => 'entries/show.pdf.erb',
                  :page_size => 'A4',
                  :footer => {:left => "spika.jubla.ch", :center => "Spielkatapult", :right => 'Seite [page] von [topage]' }
        end
      end
    end
  end

  def new
    @entry = Entry.new()
    @check_duplicates = true;
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.user = current_user
    @entry.published = (current_user.role == "writer") ? true : false
    @entry.material = remove_dash(@entry.material)
    @program_entry = ProgramEntry.new(program_entry_params) if params[:program_entry].present?

    if @entry.save
      if params[:entry][:file]
        params[:entry][:file].each do |file|
          @attachment = Attachment.create(file: file, entry: @entry)
          if @attachment.new_record?
            flash[:error] = "Fehler beim Dateiupload!"
          end
        end
      end

      if @program_entry
        @program_entry.entry = @entry
        if @program_entry.save
          program = @program_entry.program
          program = update_program_attributes(program)
          program.save
          if program.published
            flash[:alert] = "Dieser Eintrag muss noch von einem Moderator veroeffentlicht werden, bevor er in der Gruppenstunde erscheint."
          end
          redirect_to @program_entry.program
        end
      else
        redirect_to @entry
      end
    else
      flash[:error] = "Es wurden nicht alle Plichtfelder ausgefuellt!"
      render 'new'
    end
  end


  def edit
    @entry = Entry.find(params[:id])
    temp = ""
    @entry.material.split(/\r?\n/).each do |t|
      temp += "\n" unless temp == ""
      temp += "- " + t
    end
    @entry.material = temp
    @entry.keywords = @entry.keywords.split(/[\s,]/).join(',')
    @check_duplicates = false;
    if Entry.where(edited_entry: @entry).count != 0
      flash[:error] = "Dieser Eintrag wurde bereits bearbeitet, aber noch nicht freigeschaltet und kann daher zurzeit nicht bearbeitet werden."
      redirect_to @entry
    end
  end

  def update
    @entry = Entry.find(params[:id])
    if not @entry.published
      if not current_user.is_moderator?
        authorize_entry_owner @entry
      end
      @entry.update(entry_params)
      @entry.material = remove_dash(@entry.material)
      @entry.save
      if params[:entry][:file]
        params[:entry][:file].each do |file|
          @attachment = Attachment.create(file: file, entry: @entry)
          if @attachment.new_record?
            flash[:error] = "Fehler beim Dateiupload!"
          end
        end
      end
      redirect_to @entry
    else
      @entry = Entry.new(entry_params)
      @entry.user = current_user
      @entry.published = false
      @entry.material = remove_dash(@entry.material)
      @entry.edited_entry = Entry.find(params[:id])

      if @entry.save
        if params[:entry][:file]
          params[:entry][:file].each do |file|
            @attachment = Attachment.create(file: file, entry: @entry)
            if @attachment.new_record?
              flash[:error] = "Fehler beim Dateiupload!"
            end
          end
        end
        redirect_to @entry
      else
        render 'edit'
      end
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    if not @entry.published
      if not current_user.is_moderator?
        authorize_entry_owner @entry
      end
      destroy_entry
      redirect_to entries_path
    else
      if @entry.delete_comment != nil
        flash[:error] = "Dieser Eintrag wurde bereits zum entfernen markiert, aber noch nicht abgearbeitet und kann daher zurzeit nicht nochmals markiert werden."
      else
        @entry.delete_comment = params[:hint]
        @entry.delete_user = current_user
        @entry.save
        flash[:alert] = "Der Eintrag wurde markiert. Ein Moderator wird den Antrag pruefen und den Eintrag gegebenenfalls entfernen."
      end
      redirect_to @entry
    end
  end

  def keep
    @entry = Entry.find(params[:id])
    @entry.delete_comment = nil;
    @entry.save
    redirect_to @entry
  end

  def destroy_final
    destroy_entry
    redirect_to entries_path
  end

  def plan
    session[:plan_start] ||= []
    session[:plan_main] ||= []
    session[:plan_end] ||= []

    if params[:do] == 'add_start'
      unless session[:plan_start].include?(params[:id])
        session[:plan_start] << params[:id]
      end
    elsif params[:do] == 'add_main'
      unless session[:plan_main].include?(params[:id])
        session[:plan_main] << params[:id]
      end
    elsif params[:do] == 'add_end'
      unless session[:plan_end].include?(params[:id])
        session[:plan_end] << params[:id]
      end

    elsif params[:do] == 'del_start'
      session[:plan_start] -= [params[:id]]
    elsif params[:do] == 'del_main'
      session[:plan_main] -= [params[:id]]
    elsif params[:do] == 'del_end'
      session[:plan_end] -= [params[:id]]

    elsif params[:do] == 'down'
      if session[:plan_start].include?(params[:id])
        index = session[:plan_start].find_index(params[:id])
        if (index + 1) == session[:plan_start].count
          session[:plan_start] -= [params[:id]]
          session[:plan_main].unshift(params[:id]) unless session[:plan_main].include?(params[:id])
        else
          tmp = session[:plan_start][index]
          session[:plan_start][index] = session[:plan_start][index+1]
          session[:plan_start][index+1] = tmp
        end
      elsif session[:plan_main].include?(params[:id])
        index = session[:plan_main].find_index(params[:id])
        if (index + 1) == session[:plan_main].count

app/helpers/entries_helper.rb
module EntriesHelper

  def checked_glyphicons (value)

    if value then
      icon = "ok"
    else
      icon = "remove"
    end

    data = "<span class='glyphicon glyphicon-#{icon} aria-hidden='true'></span>"
    data.html_safe

  end

  def print_time (value)

    if value > 60
      "#{value/60} Stunden".html_safe
    elsif value == 60
      "1 Stunde".html_safe
    else
      "#{value} Minuten".html_safe
    end
    
  end

  def rating_comp (value, comp)

    if(value.is_a? Numeric)
      if(value <= comp)
        '-empty'
      end
    else
      '-empty'
    end

  end

end

app/views/entries/_buttons.html.erb
<div class="entry_button_area text-right">

  <% if user_signed_in? and current_user.is_moderator? %>
    <% if not @entry.published %>
      <div class="btn-group btn-space">
        <%= link_to 'Veröffentlichen', publish_entry_path(@entry), method: :post, class: "btn btn-danger btn-space" %>
      </div>
    <% end %>
    <% if @entry.delete_comment != nil %>
      <div class="btn-group btn-space">
        <%= link_to 'Löschen', destroy_final_entry_path(@entry), method: :post, class: "btn btn-danger btn-space"%>
        <%= link_to 'Behalten', keep_entry_path(@entry), method: :post, class: "btn btn-success btn-space" %>
      </div>
    <% end %>
  <% end %>

  <div class="btn-group btn-space">
    <button onclick="window.history.back();" type="button" class="btn btn-primary">Zurück</button>
  </div>
  <div class="btn-group btn-space">
    <%= link_to entry_path(@entry, :format => 'pdf'), class: "btn btn-primary btn-space", :target => '_blank' do %>
        <span class="glyphicon glyphicon-print"></span> PDF
    <% end %>
  </div>

  <div class="btn-group btn-space">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      Verwenden als
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu right_dropdown" role="menu">
      <li><%= link_to 'Einleitung', plan_entry_path(@entry, do: 'add_start'), method: :post %></li>
      <li><%= link_to 'Hauptteil', plan_entry_path(@entry, do: 'add_main'), method: :post %></li>
      <li><%= link_to 'Schluss', plan_entry_path(@entry, do: 'add_end'), method: :post %></li>
    </ul>
  </div>
  <div class="btn-group btn-space">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      Ändern
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu right_dropdown" role="menu">
      <li><%= link_to 'Bearbeiten', edit_entry_path(@entry) %></li>
      <% if @entry.published %>
        <li><a href="#" data-toggle="modal" data-target="#delete-modal-<%= id %>">Löschen beantragen</a></li>
      <% else %>
        <li><%= link_to 'Löschen', entry_path(@entry),
              method: :delete,
              data: { confirm: 'Soll dieser Eintrag wirklich gelöscht werden?' } %></li>
      <% end %>
    </ul>
  </div>

</div>

<%= form_tag(url_for(controller: "entries", action: "destroy"), method: "delete") do %>
  <div class="modal fade" id="delete-modal-<%= id %>" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Löschung eines Eintrages beantragen</h4>
        </div>
        <div class="modal-body">
          <p>Bitte gib einen Grund an, warum der Eintrag gelöscht werden soll. Die Moderatoren werden deinen Antrag prüfen und gegebenenfalls den Eintrag entfernen.</p>
          <%= label_tag(:hint, "Löschgrund:") %>
          <%= text_field_tag(:hint, '', class: "delete_hint_textfield") %>
          <i>Beispiel: Fast gleicher Eintrag ist bereits unter dem Namen XY vorhanden.</i>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
          <%= submit_tag("Löschen beantragen", class: "btn btn-danger") %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/entries/_description.html.erb
<h2>Beschreibung</h2>
<p><%= @entry.description.html_safe %></p>

<% if not @entry.material.empty? %>
  <h2>Material</h2>
  <ul>
    <% @entry.material.split(/\r?\n/).each do |t| %>
      <li><%= "#{t}" %></li>
    <% end %>
  </ul>
<% end %>

<% if not @entry.remarks.empty? %>
  <h2>Bemerkungen</h2>
  <p><%= @entry.remarks %></p>
<% end %>

<% if not @entry.preparation.empty? %>
  <h2>Vorbereitungen</h2>
  <p><%= @entry.preparation %></p>
<% end %>

app/views/entries/_details.html.erb
<h3>Geeignet als</h3>
<p>
  <%= checked_glyphicons(@entry.part_start) %> Einleitung<br>
  <%= checked_glyphicons(@entry.part_main)  %> Hauptteil<br>
  <%= checked_glyphicons(@entry.part_end)   %> Schluss
</p>

<h3>Alter</h3>
<p>
  <%= checked_glyphicons(@entry.age_5) %>  5 - 7 Jahre<br>
  <%= checked_glyphicons(@entry.age_8) %>  8 - 11 Jahre<br>
  <%= checked_glyphicons(@entry.age_12) %> 12 - 14 Jahre<br>
  <%= checked_glyphicons(@entry.age_15) %> 15 - 16 Jahre<br>
  <%= checked_glyphicons(@entry.age_17) %> 17+ Jahre<br>
</p>

<h3>Spielbar</h3>
<p>
  <%= checked_glyphicons(@entry.indoors)  %> Drinnen<br>
  <%= checked_glyphicons(@entry.outdoors) %> Draussen<br>
</p>

<h3>Spielart</h3>
<p>
  <%= checked_glyphicons(@entry.act_active)   %> Bewegt<br>
  <%= checked_glyphicons(@entry.act_calm)     %> Ruhig<br>
  <%= checked_glyphicons(@entry.act_creative) %> Kreativ<br>
  <%= checked_glyphicons(@entry.act_talk) %>     Gesprächig<br>
  <%= checked_glyphicons(@entry.act_distance) %>     ohne Körperkontakt<br>
</p>

<h3>Kategorie</h3>
<p>
  <%= checked_glyphicons(@entry.cat_game)  %> Spiel &amp; Sport<br>
  <%= checked_glyphicons(@entry.cat_shape) %> Gestalten<br>
  <%= checked_glyphicons(@entry.cat_group) %> Gruppengeist<br>
  <%= checked_glyphicons(@entry.cat_jubla) %> Jubla-Wissen<br>
</p>

<h3>Gruppengrösse</h3>
<p>
  <%= @entry.group_size_min %> - <%= @entry.group_size_max %> Kinder
</p>

<h3>Zeit</h3>
<p>
  <%= print_time(@entry.time_min) %> - <%= print_time(@entry.time_max) %>
</p>

app/views/entries/_list.html.erb
<div id="filterrific_results">

  <table class="table result-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Bewertung</th>
        <th class="hidden-xs">Details</th>
      </tr>
    </thead>

    <% if not only_programs %>
      <% entries.each do |entry| %>
        <tr>
          <td><%= link_to(entry.title, entry_path(entry)) %></td>
          <td><%= if entry.rating then entry.rating else '-' end %> (<%= entry.ratings.count %>)</td>
          <% if entry.title_other != "" %>
            <td class="hidden-xs">Weitere Namen: <%= sanitize(entry.title_other[0..200], :tags=>[]) %></td>
          <% else %>
            <td class="hidden-xs"><%= sanitize(entry.description[0..200], :tags=>[]) %></td>
          <% end %>
        </tr>
        <% if not hide_programs %>
          <% entry.programs.where(done: true, published: true).each do |program| %>
            <% if not @shown_programs.include? program %>
              <tr class="active">
                <td><%= link_to(program.title, program_path(program)) %></td>
                <td><%= if program.rating then program.rating else '-' end %> (<%= program.ratings.count %>)</td>
                <td class="hidden-xs">Gruppenstunden-Vorschlag mit dem Spiel "<%= entry.title %>"</td>
              </tr>
              <% @shown_programs << program %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

    <% else %>
      <% entries.each do |program| %>
        <tr class="active">
          <td><%= link_to(program.title, program_path(program)) %></td>
          <td><%= if program.rating then program.rating else '-' end %> (<%= program.ratings.count %>)</td>
          <td class="hidden-xs">
            <% program.entries.each_with_index do |entry, i| %>
              <%= if i==program.entries.count-1 then entry.title else "#{entry.title}, " end %>
            <% end %>
          </td>
        </tr>
      <% end %>

    <% end %>

  </table>

  <% if entries.empty? %>
    <p>Leider keine Ergebnisse gefunden</p>
  <% end %>

  <% if not only_programs %>
    <%= will_paginate entries %>
  <% else %>
    <%= will_paginate programs %>
  <% end %>

</div>

app/views/entries/_plan.html.erb
<table class="plan-list">
  <% list.each do |id| entry = Entry.find(id) %>
    <tr>
      <td>
        <%= link_to(entry.title, entry_path(entry)) %>
      </td>
      <td>
        <%= link_to plan_entry_path(entry, do: "up"), method: :post do %><span class="glyphicon glyphicon-arrow-up"/><% end %>
        <%= link_to plan_entry_path(entry, do: "down"), method: :post do %><span class="glyphicon glyphicon-arrow-down"/><% end %>
        <%= link_to plan_entry_path(entry, do: "del_#{part}"), method: :post do %><span class='glyphicon glyphicon-remove'></span><% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/entries/index.js.erb
<% js = escape_javascript(
  render(
      partial: 'entries/list',
      locals: { entries: @entries,
                programs: @programs,
                hide_programs: @hide_programs,
                only_programs: @only_programs }
    )
) %>
$("#filterrific_results").html("<%= js %>");

app/views/entries/new.html.erb
<h1>Eintrag erstellen</h1>
 
<%= render 'entries/form' %>

app/views/entries/not_published.erb
<h2>Anträge</h2>
<table class="table">
  <thead>
    <tr>
      <th>Betrifft</th>
      <th>Von</th>
      <th>Details</th>
    </tr>
  </thead>

  <% @entries_pub.each do |entry| %>
    <tr>
      <td><%= link_to(entry.title, entry_path(entry)) %></td>
      <td><%= link_to(entry.user.name, user_path(entry.user)) %></td>
      <td><%= if entry.edited_entry == nil then 'Neuer Eintrag' else 'Bearbeiteter Eintrag' end %></td>
    </tr>
  <% end %>
  <% @entries_del.each do |entry| %>
    <td><%= link_to(entry.title, entry_path(entry)) %></td>
    <td><%= link_to(entry.delete_user.name, user_path(entry.delete_user)) %></td>
    <td>Zum löschen markiert (Grund: <%= entry.delete_comment %>)</td>
  <% end %>
  <% @programs_pub.each do |program| %>
    <tr>
      <td><%= link_to(program.title, program_path(program)) %></td>
      <td><%= link_to(program.user.name, user_path(program.user)) %></td>
      <td>Neue Gruppenstunde</td>
    </tr>
  <% end %>
  <% @programs_edit.each do |program| %>
    <tr>
      <td><%= link_to(program.title, program_path(program)) %></td>
      <td><%= link_to(program.delete_user.name, user_path(program.delete_user)) %></td>
      <td>Bearbeiteter Titel</td>
    </tr>
  <% end %>
  <% @program_entry_del.each do |program_entry| %>
    <td><%= link_to(program_entry.entry.title, program_path(program_entry.program)) %></td>
    <td><%= link_to(program_entry.delete_user.name, user_path(program_entry.delete_user)) %></td>
    <td>Zum entfernen von Grustu "<%= program_entry.program.title %>" markiert (Grund: <%= program_entry.delete_comment %>)</td>
  <% end %>
  <% @programs_del.each do |program| %>
    <td><%= link_to(program.title, program_path(program)) %></td>
    <td><%= link_to(program.delete_user.name, user_path(program.delete_user)) %></td>
    <td>Zum löschen markiert (Grund: <%= program.delete_comment %>)</td>
  <% end %>
  <% @comments_pub.each do |comment| %>
    <tr>
      <% if not comment.program == nil %>
        <td><%= link_to(comment.program.title, program_path(comment.program)) %></td>
      <% else %>
        <td><%= link_to(comment.entry.title, entry_path(comment.entry)) %></td>
      <% end %>
      <td><%= link_to(comment.user.name, user_path(comment.user)) %></td>
      <td>Neuer Kommentar</td>
    </tr>
  <% end %>
  <% @comments_del.each do |comment| %>
    <% if not comment.program == nil %>
      <td><%= link_to(comment.program.title, program_path(comment.program)) %></td>
    <% else %>
      <td><%= link_to(comment.entry.title, entry_path(comment.entry)) %></td>
    <% end %>
    <td><%= link_to(comment.delete_user.name, user_path(comment.delete_user)) %></td>
    <td>Zum löschen markiert (Grund: <%= comment.delete_comment %>)</td>
  <% end %>
  <% @attachments_del.each do |attachment| %>
    <td><%= link_to(attachment.entry.title, entry_path(attachment.entry)) %></td>
    <td><%= link_to(attachment.delete_user.name, user_path(attachment.delete_user)) %></td>
    <td>Anhang zum löschen markiert (Grund: <%= attachment.delete_comment %>)</td>
  <% end %>

</table>

<% if @publish_num == 0 %>
  <p>Keine Anträge</p>
<% end %>

app/views/entries/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <h1>
      <%= @entry.title %><br>
      <small><%= @entry.title_other %></small>
    </h1>
  </div>
  <div class="col-sm-7 hidden-xs">
    <%= render partial: 'entries/buttons', locals: { id: "1" } %>
  </div>
</div>

<div class="row">
  <div class="col-sm-9">
    <%= render 'description' %>
    <%= render partial: 'attachments/list', locals: { attachments: @entry.attachments, published: @entry.published } if not @entry.attachments.empty? %>
  </div>

  <div class="col-sm-3">
    <%= render 'details' %>
    <h3>Bewertung</h3>
    <p class='rating-area'>
      <%= link_to rate_entry_path(@entry, rating: '1'), method: :post do %>
        <span class="glyphicon glyphicon-star<%= rating_comp(@entry.rating, 0.5) %>"></span>
      <% end %>
      <%= link_to rate_entry_path(@entry, rating: '2'), method: :post do %>
        <span class="glyphicon glyphicon-star<%= rating_comp(@entry.rating, 1.5) %>"></span>
      <% end %>
      <%= link_to rate_entry_path(@entry, rating: '3'), method: :post do %>
        <span class="glyphicon glyphicon-star<%= rating_comp(@entry.rating, 2.5) %>"></span>
      <% end %>
      <%= link_to rate_entry_path(@entry, rating: '4'), method: :post do %>
        <span class="glyphicon glyphicon-star<%= rating_comp(@entry.rating, 3.5) %>"></span>
      <% end %>
      <%= link_to rate_entry_path(@entry, rating: '5'), method: :post do %>
        <span class="glyphicon glyphicon-star<%= rating_comp(@entry.rating, 4.5) %>"></span>
      <% end %><br>
      <% if @entry.ratings.exists? %>
        <%= @entry.rating %> Sterne
        (<%= @entry.ratings.count %>
        <%= if@entry.ratings.count == 1 then 'Bewertung' else 'Bewertungen' end %>)
      <% else %>
        Noch keine Bewertungen
      <% end %>
    </p>
    <h2>Autor</h2>
    <% if @entry.user %>
      <p><%= link_to(@entry.user.name, user_path(@entry.user)) %></p>
    <% else %>
      Konto gelöscht
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= render partial: 'comments/create', locals: { res: @entry } %>
  </div>
</div>

<div class="row visible-xs-block">
  <div class="col-xs-12">
    <%= render partial: 'entries/buttons', locals: { id: "2" } %>
  </div>
</div>

app/views/entries/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <%= wicked_pdf_stylesheet_link_tag 'pdf_fonts' %>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
  </head>
  <body>

    <%= wicked_pdf_image_tag 'logo_pdf.png', :id => 'logo' %>
    <div id="title">
      <%= @entry.title %>
    </div>

    <div id="description">
      <%= render :template => 'entries/_description.html.erb' %>
    </div>

    <div id="details">
      <%= render :template => 'entries/_details.html.erb' %>
    </div>

  </body>
</html>