config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get 'faq', to: 'application#faq'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'new_idea', to: 'application#new_idea'
  get 'agb', to: 'application#agb'

  devise_for :users
  
  resources :users, except: [:create, :new]
  resources :news
  resources :links
  resources :pictures
  resources :pages, except: [:create, :show, :new, :destroy]

  resources :programs do
    member do
      post :rate
      get :add_existing_entry, controller: :program_entries
      get :add_new_entry, controller: :program_entries
      post :done
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :entries do
    collection do
      get :tags
      get :not_published
      get :check_duplicates
    end

    member do
      post :plan
      post :rate
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :program_entries, only: [:destroy] do
    member do
      post :move_up
      post :move_down
      post :destroy_final
      post :keep
    end
  end

  resources :comments, only: [:destroy] do
    member do
      post :publish
      post :destroy_final
      post :keep
    end
  end

  resources :attachments, only: [:destroy] do
    member do
      post :destroy_final
      post :keep
    end
  end

end

app/models/program.rb
class Program < ActiveRecord::Base
  before_destroy :destroy_entries

  has_many :program_entries, dependent: :destroy
  has_many :entries, through: :program_entries
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :delete_user, :class_name => 'User', :foreign_key => 'delete_user'

  validates :title, presence: true


  filterrific(
    default_filter_params: {
      sorted_by: 'rating_desc'
    },
    available_filters: [
      :sorted_by,
      :search_query,
      :with_part_start,
      :with_part_main,
      :with_part_end,
      :only_programs,
      :with_indoors,
      :with_outdoors,
      :with_act_active,
      :with_act_calm,
      :with_act_creative,
      :with_act_talk,
      :with_act_distance,
      :with_cat_game, 
      :with_cat_shape,
      :with_cat_group,
      :with_cat_jubla,
      :with_age_5,
      :with_age_8,
      :with_age_12,
      :with_age_15,
      :with_age_17,
      :num_group_min,
      :num_group_max,
      :num_time_min,
      :num_time_max
    ]
  )

  def self.check_boolean_attr attr_name, attr_value
    return nil  if 0 == attr_value
    where(attr_name.to_sym => true)
  end

  scope :only_programs, lambda { |flag| }
  scope :with_part_start, lambda { |flag| }
  scope :with_part_main, lambda { |flag| }
  scope :with_part_end, lambda { |flag| }
  scope :with_age_5, lambda { |flag| check_boolean_attr "age_5", flag }
  scope :with_age_8, lambda { |flag| check_boolean_attr "age_8", flag }
  scope :with_age_12, lambda { |flag| check_boolean_attr "age_12", flag }
  scope :with_age_15, lambda { |flag| check_boolean_attr "age_15", flag }
  scope :with_age_17, lambda { |flag| check_boolean_attr "age_17", flag }
  scope :with_indoors, lambda { |flag| check_boolean_attr "indoors", flag }
  scope :with_outdoors, lambda { |flag| check_boolean_attr "outdoors", flag }
  scope :with_act_active, lambda { |flag| check_boolean_attr "act_active", flag }
  scope :with_act_calm, lambda { |flag| check_boolean_attr "act_calm", flag }
  scope :with_act_creative, lambda { |flag| check_boolean_attr "act_creative", flag }
  scope :with_act_talk, lambda { |flag| check_boolean_attr "act_talk", flag }
  scope :with_act_distance, lambda { |flag| check_boolean_attr "act_distance", flag }
  scope :with_cat_game, lambda { |flag| check_boolean_attr "cat_game", flag }
  scope :with_cat_shape, lambda { |flag| check_boolean_attr "cat_shape", flag }
  scope :with_cat_group, lambda { |flag| check_boolean_attr "cat_group", flag }
  scope :with_cat_jubla, lambda { |flag| check_boolean_attr "cat_jubla", flag }

  def self.check_integer_attr attr_name, attr_value, comp
    return nil  if attr_value.blank?
    return nil  if !attr_value.is_a? Integer
    where("#{attr_name} #{comp} #{attr_value.to_s}")
  end

  scope :num_group_min, lambda { |num| check_integer_attr "group_size_min", num, "<="}
  scope :num_group_max, lambda { |num| check_integer_attr "group_size_max", num, ">="}
  scope :num_time_min, lambda { |num| check_integer_attr "time_min", num, "<="}
  scope :num_time_max, lambda { |num| check_integer_attr "time_max", num, ">="}

  scope :search_query, lambda { |query|
    return nil  if query.blank?

    where(
      "(LOWER(programs.title) LIKE :q
      OR LOWER(programs.search_text) LIKE :q
      OR LOWER(programs.material) LIKE :q
      OR LOWER(programs.remarks) LIKE :q
      OR LOWER(programs.preparation) LIKE :q)",
      :q => "%#{query}%"
    )
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'

    case sort_option.to_s
    when /^rating_/
      order("programs.rating_calc #{ direction }")
    when /^title_/
      order("LOWER(programs.title) #{ direction }")
    when /^duration_/
      order("programs.time_min #{ direction }")
    when /^id_/
      order("programs.id #{ direction }")
    else
      raise(ArgumentError, "Sortier-Option ungueltig: #{ sort_option.inspect }")
    end
  }

  private
    def destroy_entries
      entries.each do |e|
        if not e.independent
          e.destroy
        end
      end
    end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  before_action :authorize_user, except: [:show, :plan]
  before_action :authorize_moderator, only: [:publish, :keep, :destroy_final]
  
  def show
    @edit = false;
    @show_done = false

    if params[:id].to_i == 0

      @edit = true
      @plan = true
      @program = Program.new
      @program.id = 0
      @program.title = "Deine Gruppenstunde"

      @plan_start = []
      @plan_main = []
      @plan_end = []

      session[:plan_start].each do |id|
        entry = Entry.find(id)
        @program.entries << entry
        @plan_start << entry
      end
      session[:plan_main].each do |id|
        entry = Entry.find(id)
        @program.entries << entry
        @plan_main << entry
      end
      session[:plan_end].each do |id|
        entry = Entry.find(id)
        @program.entries << entry
        @plan_end << entry
      end

      @program = update_program_attributes(@program)

    else
      @plan = false
      @program = Program.find(params[:id])
      if not @program.done
        authorize_program_owner @program
        @show_done = true;
      end
    end

    @attachments = @program.entries.collect{|x| x.attachments.order(:file_content_type)}.flatten

    if params[:edit] or not @program.done
      @edit = true;
    end

    if user_signed_in? and current_user.is_moderator?
      if not @program.edited_title == nil
        @program.title = "#{@program.edited_title} (bisher: #{@program.title})"
      end
    end

    respond_to do |format|
      format.html
      format.pdf do
        render  :pdf => "Spika_Program",
                :template => 'programs/show.pdf.erb',
                :page_size => 'A4',
                :footer => {:left => "spika.jubla.ch", :center => "Spielkatapult", :right => 'Seite [page] von [topage]' }
      end
    end
  end

  def new
    @program = Program.new
  end

  def new_entry
    @entry = Entry.new
    program = Program.find(params[:program_id])

    order = params[:order].to_i
    last_program_entry = ProgramEntry.where(program: program).where(order: (order..(order+99))).order(:order).last
    order = last_program_entry.order+1 if last_program_entry
    @program_entry = ProgramEntry.new(program: program, order: order)

    render 'entries/new'
  end

  def create
    @program = Program.new(program_params)
    @program.user = current_user
    @program.search_text = ""
    @program.material = ""
    @program.preparation = ""
    @program.remarks = ""
    @program.group_size_min = 0
    @program.group_size_max = 0
    @program.age_5 = false
    @program.age_8 = false
    @program.age_12 = false
    @program.age_15 = false
    @program.age_17 = false
    @program.time_min = 0
    @program.time_max = 0
    @program.indoors = false
    @program.outdoors = false
    @program.act_active = false
    @program.act_calm = false
    @program.act_creative = false
    @program.act_talk = false
    @program.act_distance = false
    @program.cat_game = false
    @program.cat_shape = false
    @program.cat_group = false
    @program.cat_jubla = false
    @program.done = false
    @program.published = false

    if @program.save
      flash[:info] = "Gruppenstunde erstellt. Du kannst nun neue Spiele erfassen oder bestehende verwenden. Sobald du fertig bist, kannst du auf den Knopf 'Fertig' druecken."
      redirect_to @program
    else
      render 'new'
    end
  end
  
  def edit
    @program = Program.find(params[:id])
  end

  def done
    @program = Program.find(params[:id])
    authorize_program_owner @program
    @program.done = true
    @program.published = (current_user.role == "writer") ? true : false
    @program.save
    if not current_user.role == "writer"
      flash[:info] = "Deine Gruppenstunde muss nun noch von einem Moderator freigeschaltet werden, dann ist sie online."
    end
    redirect_to @program
  end

  def publish
    @program = Program.find(params[:id])

    not_ok = nil;
    @program.entries.each do |entry|
      if not entry.published then not_ok = entry.title; end
    end

    if not_ok == nil
      @program.published = true;
      if not @program.edited_title == nil
        @program.title = @program.edited_title
        @program.edited_title = nil
      end
      @program.save
      flash[:success] = "Veroeffentlicht"
    else
      flash[:error] = "Das Spiel #{not_ok} gehoert zu dieser Gruppenstunde, wurde aber noch nicht veroeffentlicht. Darum kann die Gruppenstunde auch noch nicht veroeffentlicht werden."
    end
    redirect_to @program
  end

  def update
    @program = Program.find(params[:id])

    if not @program.published
      if not @program.done
        authorize_program_owner @program
      else
        if not current_user.is_moderator?
          authorize_program_owner @program
        end
      end
      @program.title = params[:program][:title]
      if @program.save
        redirect_to @program
      else
        render 'edit'
      end
    else
      if not @program.edited_title == nil
        flash[:error] = "Der Titel wurde bereits bearbeitet, die Aenderung aber noch nicht akzeptiert. Deshalb kann der Titel zurzeit nicht nochmals bearbeitet werden."
        redirect_to @program
      else
        @program.edited_title = params[:program][:title]
        @program.delete_user = current_user

        if @program.save
          flash[:info] = "Deine Aenderung muss noch von einem Moderator ueberprueft werden, bevor sie veroeffentlicht wird."
          redirect_to @program
        else
          render 'edit'
        end
      end
    end
  end

  def destroy
    @program = Program.find(params[:id])
    if not @program.published
      if not @program.done
        authorize_program_owner @program
      else
        if not current_user.is_moderator?
          authorize_program_owner @program
        end
      end
      destroy_program
      redirect_to entries_path
    else
      @program = Program.find(params[:id])
      if @program.delete_comment != nil
        flash[:error] = "Diese Gruppenstunde wurde bereits zum entfernen markiert, aber noch nicht abgearbeitet und kann daher zurzeit nicht nochmals markiert werden."
      else
        @program.delete_comment = params[:hint]
        @program.delete_user = current_user
        @program.save
        flash[:alert] = "Die Gruppenstunde wurde markiert. Ein Moderator wird den Antrag pruefen und sie gegebenenfalls entfernen."
      end
      redirect_to @program
    end
  end

  def keep
    @program = Program.find(params[:id])
    @program.delete_comment = nil;
    @program.save
    redirect_to @program
  end

  def destroy_final
    destroy_program
    redirect_to entries_path
  end

  def rate
    @program = Program.find(params[:id])

    if @program.ratings.where(user: current_user).exists?
      flash[:error] = "Du hast diesen Eintrag bereits bewertet"
    else
      value = params[:rating].to_f
      if((value >= 1) && (value <= 5))
        @program.ratings.create(user: current_user, value: value)
        @program.rating = @program.ratings.average(:value).round(2)
        @program.rating_calc = (@program.rating - 3.0) * (1.0 + (@program.ratings.count/10.0))
        @program.save
        flash[:success] = "Bewertet mit #{params[:rating]} Sternen"
      end
    end

    redirect_to @program
  end

  private
    def program_params
      params.require(:program).permit(:title)
    end

    def destroy_program
      program = Program.find(params[:id])
      program.entries.each do |entry|
        if entry.programs.count == 1 and not entry.independent
          entry.destroy
        end
      end
      program.destroy
    end

    def authorize_program_owner (program)
      raise AuthorizationError unless program_owner?(program)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_add_button.html.erb
<div class="btn-group btn-space">
  <button type="button" class="btn btn-success btn-xs dropdown-toggle" data-toggle="dropdown">
    <span class="glyphicon glyphicon-plus"></span>
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu right_dropdown" role="menu">
    <li><%= link_to 'Neues Spiel', add_new_entry_program_path(order: order) %></li>
    <li><%= link_to 'Vorhandenes Spiel', add_existing_entry_program_path(order: order) %></li>
  </ul>
</div>

app/views/programs/_buttons.html.erb
<div class="entry_button_area text-right">

  <% if user_signed_in? and current_user.is_moderator? %>
    <% if (not @program.published and @program.done) or (not @program.edited_title == nil) %>
      <div class="btn-group btn-space">
        <%= link_to 'Veröffentlichen', publish_program_path(@program), method: :post, class: "btn btn-danger btn-space"%>
      </div>
    <% end %>
    <% if @program.delete_comment != nil %>
      <div class="btn-group btn-space">
        <%= link_to 'Löschen', destroy_final_program_path(@program), method: :post, class: "btn btn-danger btn-space"%>
        <%= link_to 'Behalten', keep_program_path(@program), method: :post, class: "btn btn-success btn-space"%>
      </div>
    <% end %>
  <% end %>

  <% if @show_done %>
    <div class="btn-group btn-space">
      <%= link_to 'Fertig', done_program_path(@program), method: :post, class: "btn btn-success btn-space"%>
    </div>
  <% end %>

  <div class="btn-group btn-space">
    <% if @edit and @program.done %>
      <%= link_to 'Fertig', program_path(@program), class: "btn btn-success btn-space"%>
    <% else %>
      <button onclick="window.history.back();" type="button" class="btn btn-primary">Zurück</button>
    <% end %>
  </div>
  <div class="btn-group btn-space">
    <%= link_to program_path(@program, :format => 'pdf'), class: "btn btn-primary btn-space", :target => '_blank' do %>
      <span class="glyphicon glyphicon-print"></span> PDF
    <% end %>
  </div>

  <% if @program.id != 0 %>
      <div class="btn-group btn-space">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
          Ändern
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu right_dropdown" role="menu">
          <li><%= link_to 'Bearbeiten', program_path(@program, :edit => true) %></li>
          <% if @program.published %>
            <li><a href="#" data-toggle="modal" data-target="#delete-modal">Löschen beantragen</a></li>
          <% else %>
            <li><%= link_to 'Löschen', program_path(@program),
                method: :delete,
                data: { confirm: 'Soll diese Gruppenstunde wirklich gelöscht werden?' } %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
  
</div>

<%= form_tag(url_for(controller: "programs", action: "destroy"), method: "delete") do %>
  <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Löschung einer Gruppenstunde beantragen</h4>
        </div>
        <div class="modal-body">
          <p>Bitte gib einen Grund an, warum die Gruppenstunde gelöscht werden soll. Die Moderatoren werden deinen Antrag prüfen und die Gruppenstunde gegebenenfalls entfernen.</p>
          <%= label_tag(:hint, "Löschgrund:") %>
          <%= text_field_tag(:hint, '', size: 75) %>
          <i>Beispiel: Die Gruppenstunde ist unvollständig.</i>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
          <%= submit_tag("Löschen beantragen", class: "btn btn-danger") %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/programs/_description.html.erb
<%= render partial: 'programs/entries', locals: {title: 'Einstieg',  start_order: 100, end_order: 199} %>
<%= render partial: 'programs/entries', locals: {title: 'Hauptteil', start_order: 200, end_order: 299} %>
<%= render partial: 'programs/entries', locals: {title: 'Ausstieg',  start_order: 300, end_order: 399} %>


<% if not @program.material.empty? %>
  <h2>Material</h2>
  <ul>
    <% @program.material.split(/\r?\n/).each do |t| %>
      <li><%= "#{t}" %></li>
    <% end %>
  </ul>
<% end %>

<% if not @program.remarks.empty? %>
  <h2>Bemerkungen</h2>
    <ul>
      <% @program.remarks.split(/\r?\n/).each do |t| %>
          <li><%= t %></li>
      <% end %>
    </ul>
<% end %>

<% if not @program.preparation.empty? %>
  <h2>Vorbereitungen</h2>
    <ul>
      <% @program.preparation.split(/\r?\n/).each do |t| %>
          <li><%= t %></li>
      <% end %>
    </ul>
<% end %>

app/views/programs/_description_plan.html.erb
<h2>Einstieg</h2>
<% @plan_start.each do |entry| %>
    <h3><%= link_to  entry.title, entry %></h3>
    <p><%= entry.description.html_safe %></p>
<% end %>

<h2>Hauptteil</h2>
<% @plan_main.each do |entry| %>
    <h3><%= link_to  entry.title, entry %></h3>
    <p><%= entry.description.html_safe %></p>
<% end %>

<h2>Ausstieg</h2>
<% @plan_end.each do |entry| %>
    <h3><%= link_to  entry.title, entry %></h3>
    <p><%= entry.description.html_safe %></p>
<% end %>

<% if not @program.material.empty? %>
  <h2>Material</h2>
  <ul>
    <% @program.material.split(/\r?\n/).each do |t| %>
      <li><%= "#{t}" %></li>
    <% end %>
  </ul>
<% end %>

<% if not @program.remarks.empty? %>
  <h2>Bemerkungen</h2>
    <ul>
      <% @program.remarks.split(/\r?\n/).each do |t| %>
          <li><%= t %></li>
      <% end %>
    </ul>
<% end %>

<% if not @program.preparation.empty? %>
  <h2>Vorbereitungen</h2>
    <ul>
      <% @program.preparation.split(/\r?\n/).each do |t| %>
          <li><%= t %></li>
      <% end %>
    </ul>
<% end %>

app/views/programs/_details.html.erb
<h3>Alter</h3>
<p>
  <%= checked_glyphicons(@program.age_5) %>  5 - 7 Jahre<br>
  <%= checked_glyphicons(@program.age_8) %>  8 - 11 Jahre<br>
  <%= checked_glyphicons(@program.age_12) %> 12 - 14 Jahre<br>
  <%= checked_glyphicons(@program.age_15) %> 15 - 16 Jahre<br>
  <%= checked_glyphicons(@program.age_17) %> 17+ Jahre<br>
</p>

<h3>Spielbar</h3>
<p>
  <%= checked_glyphicons(@program.indoors)  %> Drinnen<br>
  <%= checked_glyphicons(@program.outdoors) %> Draussen<br>
</p>

<h3>Spielart</h3>
<p>
  <%= checked_glyphicons(@program.act_active)   %> Bewegt<br>
  <%= checked_glyphicons(@program.act_calm)     %> Ruhig<br>
  <%= checked_glyphicons(@program.act_creative) %> Kreativ<br>
  <%= checked_glyphicons(@program.act_talk) %>     Gesprächig<br>
</p>

<h3>Kategorie</h3>
<p>
  <%= checked_glyphicons(@program.cat_game)  %> Spiel &amp; Sport<br>
  <%= checked_glyphicons(@program.cat_shape) %> Gestalten<br>
  <%= checked_glyphicons(@program.cat_group) %> Gruppengeist<br>
  <%= checked_glyphicons(@program.cat_jubla) %> Jubla-Wissen<br>
</p>

<h3>Gruppengrösse</h3>
<p>
  <%= @program.group_size_min %> - <%= @program.group_size_max %> Kinder
</p>

<h3>Zeit</h3>
<p>
  <%= print_time(@program.time_min) %> - <%= print_time(@program.time_max) %>
</p>

app/views/programs/_entries.html.erb
<div class="program-entries">
  <div class="row">
    <div class="col-xs-9"><h2><%= title %></h2></div>
    <div class="col-xs-3 text-right add-button"><%= render partial: 'add_button', locals: {order: start_order} if @edit and (not params[:format] == 'pdf') %></div>
  </div>

  <% @program.program_entries.order(:order).where(order: (start_order..end_order)).each do |pe| %>
    <% if pe.entry.published or (user_signed_in? and current_user.is_moderator?) or (pe.entry.user == current_user) %>
      <div class="row">
        <div class="col-xs-9"><h3><%= link_to_if (not params[:format] == 'pdf'), pe.entry.title, pe.entry %></h3></div>
        <div class="col-xs-3 text-right move-buttons">
          <% if @edit and (not params[:format] == 'pdf') %>
              <% if false %>
                  //Buttons disabled
            <%= link_to move_up_program_entry_path(pe), method: :post do %><span class="glyphicon glyphicon-arrow-up"/><% end %>
            <%= link_to move_down_program_entry_path(pe), method: :post do %><span class="glyphicon glyphicon-arrow-down"/><% end %>
              <% end %>
            <% if @program.published %>
              <a href="#" data-toggle="modal" data-target="#delete-modal-entry" data-id="<%= pe.id %>"><span class="glyphicon glyphicon-remove"/></a>
            <% else %>
              <%= link_to program_entry_path(pe), method: :delete,
                data: { confirm: 'Soll dieser Eintrag wirklich entfernt werden?' } do %>
                <span class="glyphicon glyphicon-remove"/><% end %>
            <% end %>
          <% end %>
        </div>
      </div>
      <p><%= pe.entry.description.html_safe %></p>
      <% if user_signed_in? and current_user.is_moderator? %>
        <% if pe.delete_comment != nil %>
          <div class="btn-group btn-space">
            <%= link_to 'Entfernen', destroy_final_program_entry_path(pe), method: :post, class: "btn btn-danger btn-space"%>
            <%= link_to 'Behalten', keep_program_entry_path(pe), method: :post, class: "btn btn-success btn-space"%>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<% unless request.format.to_sym == :pdf %>
  <%= form_tag(url_for(controller: "program_entries", action: "destroy"), method: "delete") do %>
    <div class="modal fade" id="delete-modal-entry" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Entfernung eines Eintrages beantragen</h4>
          </div>
          <div class="modal-body">
            <p>Bitte gib einen Grund an, warum der Eintrag aus dieser Gruppenstunde entfernt werden soll. Die Moderatoren werden deinen Antrag prüfen und gegebenenfalls den Eintrag entfernen.</p>
            <p>Hinweis: Der Eintrag selbst wird damit nicht gelöscht, er wird nur nicht mehr in dieser Gruppenstunde angezeigt.</p>
            <%= label_tag(:hint, "Löschgrund:") %>
            <%= text_field_tag(:hint, '', size: 75) %>
            <%= hidden_field_tag(:program_entry_id, '') %>
            <i>Beispiel: Ich habe einen passenderen Eintrag hinzugefügt</i>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
            <%= submit_tag("Entfernung beantragen", class: "btn btn-danger") %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <script>init_delete_modal_program_entry()</script>
<% end %>

app/views/programs/edit.html.erb
<h1>Titel bearbeiten</h1>

<%= simple_form_for @program do |p| %>
    <%= p.input :title, label: 'Titel' %>

    <%= p.button :submit, 'Speichern' %>
<% end %>

app/views/programs/new.html.erb
<h1>Gruppenstunde erstellen</h1>

<%= simple_form_for @program do |p| %>
    <%= p.input :title, label: 'Titel' %>

    <%= p.button :submit, 'Weiter' %>
<% end %>

app/views/programs/show.html.erb
<div class="row">
  <div class="col-sm-4">
    <h1>
      <%= if @edit then link_to @program.title, edit_program_path(@program) else @program.title end %>
    </h1>
  </div>
  <div class="col-sm-7 hidden-xs">
    <%= render 'buttons' %>
  </div>

</div>


<div class="row">
  <div class="col-sm-9">

    <% if @plan %>
      <%= render 'description_plan' %>
    <% else %>
      <%= render 'description' %>
    <% end %>

    <%= render partial: 'attachments/list', locals: { attachments: @attachments, published: true } unless @attachments.empty? %>

  </div>
  <div class="col-sm-3">
    <%= render 'details' %>

    <% if not @plan %>
      <h3>Bewertung</h3>
      <p class='rating-area'>
        <%= link_to rate_program_path(@program, rating: '1'), method: :post do %>
          <span class="glyphicon glyphicon-star<%= rating_comp(@program.rating, 0.5) %>"></span>
        <% end %>
        <%= link_to rate_program_path(@program, rating: '2'), method: :post do %>
          <span class="glyphicon glyphicon-star<%= rating_comp(@program.rating, 1.5) %>"></span>
        <% end %>
        <%= link_to rate_program_path(@program, rating: '3'), method: :post do %>
            <span class="glyphicon glyphicon-star<%= rating_comp(@program.rating, 2.5) %>"></span>
        <% end %>
        <%= link_to rate_program_path(@program, rating: '4'), method: :post do %>
            <span class="glyphicon glyphicon-star<%= rating_comp(@program.rating, 3.5) %>"></span>
        <% end %>
        <%= link_to rate_program_path(@program, rating: '5'), method: :post do %>
          <span class="glyphicon glyphicon-star<%= rating_comp(@program.rating, 4.5) %>"></span>
        <% end %><br>
        <% if @program.ratings.exists? %>
          <%= @program.rating %> Sterne
          (<%= @program.ratings.count %>
          <%= if@program.ratings.count == 1 then 'Bewertung' else 'Bewertungen' end %>)
        <% else %>
          Noch keine Bewertungen
        <% end %>
      </p>
      <h2>Autor</h2>
      <% if @program.user %>
        <p><%= link_to(@program.user.name, user_path(@program.user)) %></p>
      <% else %>
        Konto gelöscht
      <% end %>
    <% end %>
    
  </div>
</div>

<% if not @plan %>
  <div class="row">
    <div class="col-sm-12">
      <%= render  partial: 'comments/create', locals: { res: @program } %>
    </div>
  </div>
<% end %>

<div class="row visible-xs-block">
  <div class="col-xs-12">
    <%= render 'buttons' %>
  </div>
</div>

app/views/programs/show.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <%= wicked_pdf_stylesheet_link_tag 'pdf_fonts' %>
    <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
  </head>
  <body>

    <%= wicked_pdf_image_tag 'logo_pdf.png', :id => 'logo' %>
    <div id="title">
      <%= @program.title %>
    </div>

    <div id="description">
      <% if @plan %>
        <%= render :template => 'programs/_description_plan.html.erb' %>>
      <% else %>
        <%= render :template => 'programs/_description.html.erb' %>
      <% end %>
    </div>

    <div id="details">
      <%= render :template => 'programs/_details.html.erb' %>
    </div>

  </body>
</html>