config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get 'faq', to: 'application#faq'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'new_idea', to: 'application#new_idea'
  get 'agb', to: 'application#agb'

  devise_for :users
  
  resources :users, except: [:create, :new]
  resources :news
  resources :links
  resources :pictures
  resources :pages, except: [:create, :show, :new, :destroy]

  resources :programs do
    member do
      post :rate
      get :add_existing_entry, controller: :program_entries
      get :add_new_entry, controller: :program_entries
      post :done
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :entries do
    collection do
      get :tags
      get :not_published
      get :check_duplicates
    end

    member do
      post :plan
      post :rate
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :program_entries, only: [:destroy] do
    member do
      post :move_up
      post :move_down
      post :destroy_final
      post :keep
    end
  end

  resources :comments, only: [:destroy] do
    member do
      post :publish
      post :destroy_final
      post :keep
    end
  end

  resources :attachments, only: [:destroy] do
    member do
      post :destroy_final
      post :keep
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :ratings
  has_many :comments, dependent: :destroy
  has_many :programs
  has_many :entries

  validates :name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: { user: 0, writer: 1, moderator: 2, admin: 3 }
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  def is_user?
    self.user? || self.is_writer?
  end

  def is_writer?
    self.writer? || self.is_moderator?
  end

  def is_moderator?
    self.moderator? || self.is_admin?
  end

  def is_admin?
    self.admin?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize_moderator, only: :index

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if not @user == current_user
      authorize_moderator
    end
  end

  def update
    @user = User.find(params[:id])
    if not @user == current_user
      authorize_moderator
    end

    if current_user.is_moderator? or @user.valid_password?(params[:user][:current_password])
      if params[:user][:role] != nil and params[:user][:role] != @user.role
        @user.role = params[:user][:role]
        authorize_update(@user)
      end
      if @user == current_user or current_user.is_admin?
        if @user.update(params[:user][:password] == "" ? user_params : user_params_pwd)
          flash[:success] = "Der Benutzer wurde geaendert"
          redirect_to @user
        else
          render 'edit'
        end
      else
        flash[:success] = "Der Benutzer wurde geaendert"
        redirect_to @user
      end
    else
      @user.errors.add(:current_password, "Dein Passwort stimmt nicht")
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    if not user == current_user
      authorize_admin
    end
    user.destroy
    flash[:success] = 'Der Benutzer wurde entfernt'
    if current_user == user
      redirect_to root_path
    else
      redirect_to users_url
    end
  end

  private
    def authorize_update (user)
      raise AuthorizationError unless current_user.is_admin? or
                                      (current_user.is_moderator? and
                                          user.role != 'admin' and
                                          user.role_was != 'admin')
    end
    def user_params
      params.require(:user).permit( :first_name,
                                    :last_name,
                                    :name,
                                    :email)
    end
    def user_params_pwd
      params.require(:user).permit( :first_name,
                                    :last_name,
                                    :name,
                                    :email,
                                    :password,
                                    :password_confirmation)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def get_role_label (role)
    color = {
        :user      => 'default',
        :writer    => 'default',
        :moderator => 'primary',
        :admin     => 'danger'
    }[role.to_sym]
    german = {
        :user      => 'Benutzer',
        :writer    => 'Schreiber',
        :moderator => 'Moderator',
        :admin     => 'Administrator'
    }[role.to_sym]

    ('<span class="label label-' + color + '">' + german + '</span>').html_safe
  end
end

app/views/users/edit.html.erb
<h1><%= @user.name %> bearbeiten</h1>

<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <% if @user == current_user or current_user.is_admin? %>
    <%= f.input :first_name, required: true, autofocus: true, label: 'Vorname' %>
    <%= f.input :last_name, required: true, label: 'Nachname' %>
    <%= f.input :name, required: true, label: 'Spitzname' %>
    <%= f.input :email, required: true %>
  <% end %>

  <% if current_user.is_moderator? %>
    <%= f.input :role, include_blank: false %>
  <% end %>

  <% if @user == current_user or current_user.is_admin? %>
    <%= f.input :password, autocomplete: "off", hint: "leer lassen, falls du das Passwort nicht ändern willst", required: false, label: 'Neues Passwort'  %>
    <%= f.input :password_confirmation, required: false, label: 'Neues Passwort wiederholen'  %>
  <% end %>

  <% if not current_user.is_moderator? %>
    <%= f.input :current_password, required: true, label: 'Aktuelles Passwort' %>
  <% end %>

  <%= f.button :submit, "Bearbeiten" %>
<% end %>

<% if @user == current_user or current_user.is_admin? %>
  <hr>
  <p>Unglücklich? <%= link_to 'Account löschen', user_path(@user),
                method: :delete,
                data: { confirm: 'Willst du deinen Account beim Spielkatapult wirklich löschen?' } %></p>
<% end %>

app/views/users/index.html.erb
<h1>Benutzer</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th class="hidden-xs">E-Mail</th>
    <th>Rolle</th>
  </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= link_to user.name, user_path(user)  %></td>
            <td class="hidden-xs"><%= user.email %></td>
            <td><%= get_role_label(user.role) %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<div class="row">
  <h1 class="col-sm-12"><%= @user.name %></h1>
</div>

<div class="row">
  <% if user_signed_in? and (current_user.is_moderator? or @user==current_user) %>
    <div class="col-sm-2">Vorname:</div>
    <div class="col-sm-10"><%= @user.first_name %></div>
    <div class="col-sm-2">Nachname:</div>
    <div class="col-sm-10"><%= @user.last_name %></div>
    <div class="col-sm-2">E-Mail:</div>
    <div class="col-sm-10"><%= @user.email %></div>
  <% end %>
  <div class="col-sm-2">Rolle:</div>
  <div class="col-sm-10"><%= get_role_label(@user.role) %></div>
</div>

<% if user_signed_in? and (current_user.is_moderator? or @user==current_user) %>
  <br/>
  <div class="row">
    <span class="col-sm-12">
      <%= link_to edit_user_path(@user), class: 'btn btn-xs btn-success' do %>
        <span class="glyphicon glyphicon-pencil"></span> Bearbeiten
      <% end %>
    </span>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <h2>Erstellte Gruppenstunden</h2>
    <% if @user.entries.count == 0 and @user.programs.count == 0 %>
      <p>Dieser Benutzer hat noch keine Gruppenstunden erstellt.</p>
    <% else %>
      <table class="table table-striped table-responsive">
        <% @user.entries.each do |entry| %>
          <tr>
            <td><%= link_to(entry.title, entry_path(entry)) %></td>
          </tr>
        <% end %>
        <% @user.programs.each do |program| %>
          <tr>
            <td><%= link_to(program.title, program_path(program)) %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>

<%= link_to "Zurück", :back %>