config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  get 'faq', to: 'application#faq'
  get 'about', to: 'application#about'
  get 'contact', to: 'application#contact'
  get 'new_idea', to: 'application#new_idea'
  get 'agb', to: 'application#agb'

  devise_for :users
  
  resources :users, except: [:create, :new]
  resources :news
  resources :links
  resources :pictures
  resources :pages, except: [:create, :show, :new, :destroy]

  resources :programs do
    member do
      post :rate
      get :add_existing_entry, controller: :program_entries
      get :add_new_entry, controller: :program_entries
      post :done
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :entries do
    collection do
      get :tags
      get :not_published
      get :check_duplicates
    end

    member do
      post :plan
      post :rate
      post :publish
      post :destroy_final
      post :keep
    end

    resources :comments, only: [:create]
  end

  resources :program_entries, only: [:destroy] do
    member do
      post :move_up
      post :move_down
      post :destroy_final
      post :keep
    end
  end

  resources :comments, only: [:destroy] do
    member do
      post :publish
      post :destroy_final
      post :keep
    end
  end

  resources :attachments, only: [:destroy] do
    member do
      post :destroy_final
      post :keep
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include AuthorizationHelper
  rescue_from AuthorizationError, with: :user_not_authorized

  before_action :configure_permitted_parameters_for_devise, if: :devise_controller?

  before_filter :load_links
  before_filter :publish_num
  before_filter :unfinished_programs

  def load_links
    @links = Link.all()
  end

  def publish_num
    if user_signed_in? and current_user.is_moderator?
      @publish_num = Entry.where(published: false).count
      @publish_num += Entry.where.not(delete_comment: nil).count;
      @publish_num += Program.where(done: true, published: false).count;
      @publish_num += Program.where.not(edited_title: nil).count;
      @publish_num += ProgramEntry.where.not(delete_comment: nil).count;
      @publish_num += Program.where.not(delete_comment: nil).count;
      @publish_num += Comment.where(published: false).count
      @publish_num += Comment.where.not(delete_comment: nil).count;
      @publish_num += Attachment.where.not(delete_comment: nil).count;
    end
  end

  def unfinished_programs
    @unfin_programs = false
    if user_signed_in?
      if current_user.programs.where(done: false).count > 0
        @unfin_programs = true
        @unfin_programs_ref = current_user.programs.where(done: false);
      end
    end
  end

  def index
    @entries = Entry.where(published: true).last(5).reverse
    @news = News.paginate(:page => params[:page], :per_page => 3).order('id DESC')
    @pictures = Picture.all.reverse
  end

  def about
    @page = Page.where(title: 'Ueber uns').first
  end

  def contact
    @page = Page.where(title: 'Kontakt').first
  end

  def faq
    @page = Page.where(title: 'FAQ').first
  end

  def agb
    @page = Page.where(title: 'AGB').first
  end

  def new_idea

  end

  def update_program_attributes(program)
    program.search_text = ""
    program.material = ""
    program.preparation = ""
    program.remarks = ""
    program.group_size_min = 2
    program.group_size_max = 100
    program.age_5 = false
    program.age_8 = false
    program.age_12 = false
    program.age_15 = false
    program.age_17 = false
    program.time_min = 0
    program.time_max = 0
    program.indoors = false
    program.outdoors = false
    program.act_active = false
    program.act_calm = false
    program.act_creative = false
    program.act_talk = false
    program.cat_game = false
    program.cat_shape = false
    program.cat_group = false
    program.cat_jubla = false
    program.entries.each do |entry|
      program.search_text += " " + entry.title
      program.search_text += " " + entry.title_other
      program.search_text += " " + entry.description
      program.search_text += " " + entry.keywords
      if not entry.material.empty? then
        program.material += "\n" unless program.material.empty?
        program.material += entry.material
      end
      if not entry.preparation.empty? then
        program.preparation += "\n" unless program.preparation.empty?
        program.preparation += entry.preparation
      end
      if not entry.remarks.empty? then
        program.remarks += "\n" unless program.remarks.empty?
        program.remarks += entry.remarks
      end
      program.group_size_min = [program.group_size_min, entry.group_size_min].max
      program.group_size_max = [program.group_size_max, entry.group_size_max].min
      program.age_5 = program.age_5 || entry.age_5
      program.age_8 = program.age_8 || entry.age_8
      program.age_12 = program.age_12 || entry.age_12
      program.age_15 = program.age_15 || entry.age_15
      program.age_17 = program.age_17 || entry.age_17
      program.time_min += entry.time_min
      program.time_max += entry.time_max
      program.indoors = program.indoors || entry.indoors
      program.outdoors = program.outdoors || entry.outdoors
      program.act_active = program.act_active || entry.act_active
      program.act_calm = program.act_calm || entry.act_calm
      program.act_creative = program.act_creative || entry.act_creative
      program.act_talk = program.act_talk || entry.act_talk
      program.cat_game = program.cat_game || entry.cat_game
      program.cat_shape = program.cat_shape || entry.cat_shape
      program.cat_group = program.cat_group || entry.cat_group
      program.cat_jubla = program.cat_jubla || entry.cat_jubla
    end
    return program
  end

  protected
  def configure_permitted_parameters_for_devise
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
  end

  private
    def user_not_authorized
      flash[:alert] = 'Leider bist du nicht angemeldet oder hast keine Berechtigung fuer diese Aktion.'
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for (flash_type)
    case flash_type
      when 'success'
        'success'
      when 'error'
        'danger'
      when 'alert'
        'warning'
      when 'notice'
        'info'
      else
        flash_type.to_s
    end
  end
end

app/views/application/_structured_data.html.erb
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "SoftwareApplication",
    "applicationCategory": "Ideensammlung", 
    "operatingSystem": "all",
    "name": "Spielkatapult Jungwacht Blauring",
    "description": "Eine Sammlung von Spielideen für Leitende von Jugwacht Blauring",
    "url": "http://spika.jubla.ch",
    "image": "http://spika.jubla.ch/assets/logo_blau-b9e48fe371171789e31db6f5903b9b51.png",
    "thumbnailUrl": "http://spika.jubla.ch/assets/logo-9b0d06bf467c211f624162b35d9455ab.png",
    "sameAs" : [
      "https://www.facebook.com/spielkatapult.jungwacht.blauring"
    ],
    "audience": "Leitende von Jungwacht Blauring",
    "keywords": "Spiele, Gruppenstunden, Spiekatapult, Spika, Ideensammlung, Jungwacht, Blauring, Jubla, Jugendorganisation",
    "potentialAction": {
      "@type": "SearchAction",
      "target": "http://spika.jubla.ch/entries?filterrific[search_query]={search_term_string}",
      "query-input": "required name=search_term_string"
    }
  }
</script>

app/views/application/about.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Über uns</h1>
    <%= @page.text.html_safe %>
  </div>
</div>

app/views/application/agb.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Allgemeine Geschäftsbedingungen</h1>
    <%= @page.text.html_safe %>
  </div>
</div>

app/views/application/contact.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Kontakt</h1>
    <%= @page.text.html_safe %>
  </div>
</div>

app/views/application/faq.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Häufig gestellte Fragen</h1>
    <%= @page.text.html_safe %>
  </div>
</div>

app/views/application/index.html.erb
<div id="start-carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <% @pictures.each_with_index do |picture, i| %>
      <li data-target="#start-carousel" data-slide-to="<%= i %>" <%= if(i == 0) then "class='active'".html_safe end %>></li>
    <% end %>
  </ol>

  <div class="carousel-inner" role="listbox">
    <% @pictures.each_with_index do |picture, i| %>
      <div class="item <%= if(i == 0) then "active" end %>">
        <%= image_tag picture.file.url(:original) %>
      </div>
    <% end %>
  </div>

  <a class="left carousel-control" href="#start-carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Zurück</span>
  </a>
  <a class="right carousel-control" href="#start-carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Weiter</span>
  </a>
</div>

<div class="jumbotron">
    <div class="row">
      <div class="col-sm-6 text-center button-start-area">
          <%= link_to 'Suchen', entries_path, class: "btn btn-primary btn-xlarge"%><br/>
          Nach einer Idee suchen
      </div>
      <div class="col-sm-6 text-center button-start-area">
          <%= link_to 'Erstellen', new_idea_path, class: "btn btn-primary btn-xlarge"%><br/>
          Selber Einträge erstellen
      </div>
    </div>
</div>

<div class="row">
  <div class="col-sm-8">

    <h1>News</h1>
    <% @news.each do |news| %>
      <h2><%= news.title %></h2>
      <p><%= news.text.html_safe %></p>
      <hr>
    <% end %>
    <%= will_paginate @news, :previous_label => 'Neuer', :next_label => 'Älter'  %>

    <h1>Like us</h1>
    <div class="fb-like" data-href="https://www.facebook.com/spielkatapult.jungwacht.blauring" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

  </div>

  <div class="col-sm-4">

    <h1>Neueste Gruppenstunden</h1>
    <ul>
      <% @entries.each do |entry| %>
        <li><%= link_to(entry.title, entry_path(entry)) %></li>
      <% end %>
    </ul>

    <h1>Links</h1>
    <ul>
      <% @links.each do |link| %>
        <li><a href="<%= link.url %>" target="_blank"><%= link.title %></a></li>
      <% end %>
    </ul>

    <img class="spika-logo-big" src="<%= image_path('logo_blau.png') %>"/>

  </div>
</div>

<%= render 'structured_data' %>

app/views/application/new_idea.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-sm-6 text-center button-start-area">
      <%= link_to 'Spiel', new_entry_path, class: "btn btn-primary btn-xlarge", style: "width: 230px !important" %><br/>
      Ein einzelnes Spiel erfassen
    </div>
    <div class="col-sm-6 text-center button-start-area">
      <%= link_to 'Gruppenstunde', new_program_path, class: "btn btn-primary btn-xlarge", style: "width: 230px !important" %><br/>
      Eine ganze Gruppenstunde erfassen
    </div>
  </div>
</div>

app/views/application/theory.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Wie plane ich eine Gruppenstunde?</h1>
    <%= @page.text.html_safe %>
  </div>
</div>